#! /bin/sh

feh --bg-fill --randomize ~/Pictures/*
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V 

bspc config border_width       2 
bspc config window_gap         16 

bspc config split_ratio          50 
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on

bspc rule -a Screenkey manage=off
   
bspc rule -a burpsuite state=floating follow=on
#bspc rule -a zap.sh manage=off

# extra config 
picom --experimental-backends &
bspc config border_width 0
xsetroot -cursor_name left_ptr &

